services:
    mural_server:
        image: ghcr.io/mural-sync/mural-server
        container_name: mural_server
        ports:
            - 46666:46666
        volumes:
            - ./config:/config
        environment:
            - MURAL_SERVER_CONFIG_HOME=/config
