name: Create release

on:
  workflow_dispatch:

jobs:
  define-matrix:
    name: Define the target matrix
    runs-on: ubuntu-latest

    outputs:
      targets: ${{ steps.targets.outputs.targets }}

    steps:
      - name: Define the target matrix
        id: targets
        run: |
          echo 'targets=["x86_64-unknown-linux-musl"]' >> "$GITHUB_OUTPUT"
          
  build-binaries:
    needs:
      - define-matrix

    strategy:
      matrix:
        target: ${{ fromJson(needs.define-matrix.outputs.targets) }}
    
    name: Build binary for ${{ matrix.target }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}

      - name: Install musl dependencies
        if: matrix.target == "x86_64-unknown-linux-musl"
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ github.event.repository.name }}
